version: '3.8'

services:
  discord-transcription-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-transcription-bot
    restart: unless-stopped

    # Environment variables from .env file
    env_file:
      - .env

    # Volume mounts for persistent data
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Network (optional)
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

# Optional: Add volume for shared data
volumes:
  bot-data:
    driver: local
